spring:
  application:
    name: api

  profiles:
    active: @spring.profiles.active@
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  messages:
    basename: static/i18n/messages #相对路径 首部不要添加斜杠
  # 时间默认转时间戳
  jackson:
    serialization:
      write-dates-as-timestamps: true



  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  port: 8081
  servlet:
    context-path: /thp-api

#logging:
#  config: classpath:log/logback-spring.xml

# 订时任务
